name: Run Daily Scraping

on:
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 02:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Save Google creds
        run: |
          echo "${{ secrets.GOOGLE_CREDS }}" > google-creds.json

      - name: Run all script
  run: |
    echo "Esecuzione scraping_eventifvg.py"
    python scraping_eventifvg.py

    echo "Esecuzione scraping_itinerarinellarte.py"
    python scraping_itinerarinellarte.py

    echo "Esecuzione scraping_turismofvg.py"
    python scraping_turismofvg.py

    echo "Esecuzione unione_dati_scraping.py"
    python unione_dati_scraping.py
