name: Scraping Itinerarinellarte

on:
  schedule:
    - cron: '0 9 * * 1' # Esegui ogni lunedì alle 09:00 UTC
  workflow_dispatch: # Permette di eseguire manualmente il workflow

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Puoi specificare un'altra versione se necessario

      # Installa le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Esegui lo script di scraping
      - name: Run scraping_itinerarinellarte.py
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        run: |
          python scraping_itinerarinellarte.py
